### PR TITLE
Update scala 2.13.0-MC5 to 2.13.0-RC1

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by lihaoyi** [comment]
no idea but looks ok

**Comment by alexarchambault** [comment]
@lihaoyi Can you tag a new release in order to publish acyclic for `2.13.0-RC1`? Just creating a tag / release on github should be enough to trigger the release on the CI.

**Comment by alexarchambault** [comment]
Actually, I have the rights to tag it myself… (Will do in a few hours I guess, if that's ok.)

**Comment by lihaoyi** [comment]
go ahead!

**Pull request merged**
